version: '3'
services:
     app:
       image: jair23/01_redis_api_app
       container_name: node_app
       ports:
         - "3000:3000"
       environment:
         - REDIS_URL=redis://redis01:6379
       depends_on:
         - redis
       volumes:
          - .:/usr/src/app
          - /usr/src/app/node_modules
       command: npm start
   
     redis:
       image: redis/redis-stack:latest
       container_name: redis01
       ports:
         - "6379:6379"
         - "8001:8001"
       volumes:
         - "C:/Users/linit/OneDrive/Trabajos TEC/Trabajos TEC/Semestre 9/NoSql/redisdb:/data"